@startuml
class Inventor

class Idea

class Tecnologia

class Prototipo

class Mercado

class Innovacion

Inventor --> Idea : "crea"
Inventor --> Tecnologia : "utiliza"
Inventor --> Prototipo : "desarrolla"
Prototipo --> Mercado : "presenta a"
Mercado --> Innovacion : "genera"
@enduml
