@startuml

title Modelo del Dominio: Elección de Delegado

' Entidad Votante
class Votante {
  +ID_Votante : int
  +Nombre : String
  +Apellido : String
  +Estado_votación : Boolean

  + void votar()
}

' Entidad Candidato
class Candidato {
  +ID_Candidato : int
  +Nombre : String
  +Apellido : String
  +Total_votos : int
  +Gana : Boolean
  +void postularse()

}

' Entidad Elección
class Elección {
  +ID_Elección : int
  +Fecha_inicio : Date
  +Fecha_fin : Date
  +Tipo : String
  +Estado : String
  +Total_votos : int
   +void iniciar()
    +void finalizar()



}

class secretario {
  +ID_Secretario : int
  +Nombre : String
  +Apellido : String
  +void contar_votos()
}

' Entidad Voto
class Voto {
  +ID_Voto : int
  +Fecha_hora : DateTime
}

class Presidente {
  +ID_Presidente : int
  +Nombre : String
  +Apellido : String
  +void anunciar_ganador()
}

' Relaciones
Votante  -- Voto : emite
Candidato  -- Voto : recibe
Elección  --  Voto : contiene
Elección --  Candidato : incluye
Elección --  Votante : permite
Elección --  secretario : permite
secretario -- Elección : cuenta
Presidente -- Elección : consulta
Votante -- Candidato : vota
Candidato -- Elección : postula
Presidente -- Elección : dirige
Presidente -- Candidato : anuncia ganador


@enduml