@startwbs

+ **ASIGNATURA**
 + Repo
  + **temario**
   + casosDeUso
   + ejercicios
   + <i>otrasCarpetas...</i>
  + <b>entregas</b>
   + apellidoNombre
    +_ archivo
    +_ archivo
    +_ ...
  + evaluaciones
  + images
  + modelosUML


@endwbs