@startuml

    Package "Liderazgo" {
        Lider -- Equipo : "lidera"
        Equipo -- Objetivo : "trabaja hacia"
        Lider -- Motivacion : "proporciona"
        Motivacion -- Equipo : "influye"
    }

@enduml
