@startuml
[*] --> EsperandoVotante

EsperandoVotante --> Votando : Votante llega
Votando --> RecuentoVotos : Voto emitido
RecuentoVotos --> Resultado : Recuento completado
Resultado --> Delegado : Delegado recibe resultado
Delegado --> Fin : Proceso terminado
@enduml

