@startuml
[*] --> Inicio
Inicio --> ProcesoDeCandidatos : Definir candidatos
ProcesoDeCandidatos --> Votacion : Realizar votación
Votacion --> ConteoDeVotos : Finaliza votación
ConteoDeVotos --> AnuncioGanador : Secretario cuenta votos
AnuncioGanador --> Fin : Ganador anunciado
@enduml
