@startuml

class Clase {
  
}

class Votacion {

}

class Resultado {
}

class Estudiante {

}

class Candidato {
  
}

class Voto {
}

class MesaElectoral{

}

Clase -- Votacion
Clase -- MesaElectoral
MesaElectoral --Votacion
MesaElectoral -- Voto
MesaElectoral -- Resultado
MesaElectoral .. Estudiante
Votacion -- Candidato
Votacion -- Voto
Votacion -- Resultado
Resultado -- Candidato
Estudiante -- Voto
Voto -- Candidato
Estudiante -- Candidato
Clase .. Resultado
Clase--Estudiante
Estudiante..Votacion

@enduml
