@startuml

class Federación {
}

class Reglas {
}

class Árbitro {
}
class Tarjetas {
}


class Entrenador {
}

class Equipo {
}

class Jugadores {
}

class Aficionados {
}

class Jornada {
}

class Estadio {
}

class Salario {
}

class Temporada {
}

class Ranking {
}

Federación -- Reglas : "define"
Federación -- Árbitro : "supervisa"
Federación -- Jornada : "organiza"
Jornada -- Equipo : "compite"
Jornada -- Árbitro : "arbitra"
Jornada -- Estadio : "se juega en"
Equipo -- Jugadores : "tiene"
Equipo -- Entrenador : "dirigido por"
Equipo .. Estadio : "tiene"
Aficionados -- Estadio : "asisten a"
Aficionados .. Entrenador : "fan de"
Aficionados .. Jugadores : "fan de"
Aficionados -- Equipo : "seguidor"
Jugadores -- Salario : "reciben"
Entrenador -- Salario : "reciben"
Árbitro -- Salario : "reciben"
Árbitro -- Reglas : "aplica"
Entrenador -- Jugadores : "influye en"
Temporada -- Jornada : "incluye"
Temporada -- Ranking : "hay"
Jornada .. Ranking : "cambia"
Equipo -- Ranking : "clasifica"
Tarjetas -- Reglas : "aplica"
Tarjetas -- Árbitro : "usa"
Tarjetas .. Jugadores : "hacia"
Tarjetas .. Entrenador : "hacia"

@enduml
