@startuml
object Persona {
  
}

object Meta {
}

object Motivo {
}

object Accion {
}

object Emocion {
}

object Resultado {
  
}

Persona -- Motivo : " impulsado por"
Motivo -- Meta : " enfocado en"
Persona -- Accion : " realiza"
Accion -- Meta : " dirigida a"
Emocion -- Persona : " influye a"
Accion -- Resultado : " produce"
Persona -- Resultado : " experimenta"
Resultado -- Emocion : " provoca"
@enduml
