@startuml

package Eco {
  class "FuenteDeSonido" as FuenteDeSonido
  class "OndaSonora" as OndaSonora
  class "MedioDePropagación" as MedioDePropagación
  class "SuperficieReflectora" as SuperficieReflectora
  class "Receptor" as Receptor
  class "Eco" as Eco


  FuenteDeSonido --- OndaSonora : "genera >"
  OndaSonora --- MedioDePropagación : "viaja a través de >"
  MedioDePropagación --- SuperficieReflectora : "impacta en >"
  OndaSonora --- Receptor : "llega a >"
  Eco --- Receptor : "llega a >"
  SuperficieReflectora --- Eco : "refleja y causa >"
}
@enduml

