@startuml Dos fuentes una Persona

object persona1 {
}

object fuenteDeLuz1 {
}

object fuenteDeLuz2 {
}


object sombra1 {
}

object sombra2 {
}

fuenteDeLuz1 --> persona1
fuenteDeLuz2 --> persona1

persona1 --> sombra1
persona1 --> sombra2

fuenteDeLuz1 -[dashed]-> sombra1
fuenteDeLuz2 -[dashed]-> sombra2


@enduml