@startuml

class Sombra {
  - forma
  - intensidad
  - posición
  - tamaño
}

class Objeto {
  - posición
  - tamaño
  - orientación
}

class Luz {
  - intensidad
  - dirección
  - tipo
}

class Superficie {
  - material
  - tamaño
  - textura
}

Luz --> Objeto: Enfoca a
Objeto --> Sombra: Proyecta la
Sombra ..> Superficie : Sobre la
@enduml
