@startuml
Object FuenteDeLuz1{
}

Object FuenteDeLuz2{
}

Object Persona1 {
}

Object Persona2 {
}

Object Sombra1 {
}

Object Sombra2 {
}

Object Sombra3 {
}

Object Sombra4 {
}

Object Superficie {
}

FuenteDeLuz1--> Persona1 : ilumina
FuenteDeLuz1--> Persona2 : ilumina

FuenteDeLuz2 --> Persona1 : ilumina
FuenteDeLuz2 --> Persona2 : ilumina

Persona1 --> Sombra1 : proyecta por FuenteDeLuz1
Persona1 --> Sombra2 : proyecta por FuenteDeLuz2 

Persona2 --> Sombra3 : proyecta por FuenteDeLuz1
Persona2 --> Sombra4 : proyecta por FuenteDeLuz2 

Sombra1 --> Superficie : se proyecta sobre
Sombra2 --> Superficie : se proyecta sobre
Sombra3 --> Superficie : se proyecta sobre
Sombra4 --> Superficie : se proyecta sobre
@enduml