@startuml
class Sombra {
   
}

class Objeto {
    
}

class Superficie {
}

class Luz {
   
}

Sombra --> Objeto : proyectada por
Sombra --> SinLuz: no existe
Sombra --> Superficie : sobre
Sombra --> Luz : depende de
SinLuz --> SinSombra : Objeto y Superficie presentes
SinSombra --> Aparece : Luz encendida
Aparece --> Movimiento : Objeto se mueve
Movimiento --> Estatica : Objeto quieto
Estatica --> Movimiento : Objeto se mueve
Aparece --> Desaparece : Luz apagada
Desaparece --> SinLuz : No hay luz

@enduml
