@startuml
class Equipo

class Entrenador

class Jugador

class Arbitro

class Reglas

class Jornada

class Estadio

class Temporada

class Partido

class Resultado

class Aficionado

Equipo "1" -- "1" Entrenador : dirige >
Equipo "1" -- "0..*" Jugador : conforma >
Jornada "1" -- "1" Equipo : participa en >
Jornada "1" -- "1" Arbitro : arbitra >
Jornada "1" -- "1" Estadio : juega en >
Arbitro -- Reglas : usa >

Temporada "1" -- "0..*" Jornada : contiene >
Jornada "1" -- "0..*" Partido : contiene >
Partido "1" -- "1" Resultado : genera >
Aficionado "0..*" -- "1" Equipo : apoya >
@enduml
