@startuml
package "Sombra" {

    FocoDeLuz ..> Sombra : "Genera"

    FocoDeLuz --> Objeto : "Ilumina"

    Objeto --> Sombra : "Proyecta"

    Objeto <-- Sombra 

    Sombra ..> Superficie: "Se proyecta"

}
@enduml