@startuml

class Productor
class consumidor
class repartidor
class almacen
class pedido
class producto
class establecimiento
class empresa_secundaria


consumidor --> producto : se quiere producto acabado
establecimiento --> producto : tiene producto acabado
establecimiento --> almacen : mira en almacen
almacen --> producto : tiene producto acabado
Establecimiento --> pedido : hace pedido a empresa secundaria
empresa_secundaria --> pedido : recibe pedido
empresa_secundaria --> almacen : mira en almacen
almacen --> producto : tiene producto acabado
empresa_secundaria --> pedido : hace pedido a productor
productor --> pedido : recibe pedido
productor --> producto : tiene producto
productor --> pedido : enviar pedido a repartidor
repartidor --> pedido : recibe pedido
repartidor --> empresa_secundaria : envia pedido
empresa_secundaria --> pedido : recibe pedido y envia a establecimiento
repartidor --> establecimiento : envia pedido de empresa_secundaria
establecimiento --> pedido : recibe pedido
establecimiento --> producto : tiene producto
establecimiento --> establecimiento : hace restock
establecimiento --> almacen : mira en almacen
consumidor --> establecimiento : compra producto
consumidor --> producto : recibe producto






@enduml