@startuml
object Persona1
object Persona2
object Foco1
object Foco2
object Sombra1
object Sombra2
object Superficie

Persona1 --> Sombra1 : "proyecta"
Persona2 --> Sombra2 : "proyecta"
Foco1 --> Sombra1 : "genera"
Foco2 --> Sombra2 : "genera"
Sombra1 --> Superficie : "se proyecta en"
Sombra2 --> Superficie : "se proyecta en"
@enduml
