    @startuml
    class FuenteDeLuz {
    }

    class Objeto {
    }

    class Sombra {
    }

    class Superficie {
    }

    FuenteDeLuz  --  Objeto : ilumina sobre >
    Objeto  --  Sombra : genera >
    Sombra  --  Superficie : se proyecta sobre >
    @enduml
